apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-container
        image: {{ .Values.frontendImage | quote }}
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 90
      targetPort: 3001