apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.dbUser | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.dbPassword | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.dbName | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres  
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432